[package]
name        = "shared"
version     = "0.1.0"
edition     = "2021"
authors     = ["team-fortress@versotile.org"]
description = ""
license     = "Apache-2.0"
keywords    = ["security","cryptography","virtualization"]




[dependencies]
